---
title: "Module 0: Introduction"
subtitle: "Course Overview"
author: Ian McCarthy | Emory University
date: Econ 372 #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{graphicx}
  - \usepackage{amsmath}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size, maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(dplyr.summarise.inform = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel)
```


# Goals of this course
1. Explain structure of U.S. health care system

2. Model adverse selection in health insurance

3. Explain physician agency problem and the role of financial incentives in health care

4. Analyze hospital data in real-life setting


---
# Structure
Material typically presented as follows:

1. Traditional lecture and discussion
  - All readings listed in syllabus
  - Available on course website or *Canvas* if not publicly available
2. In-class worksheets
3. Homework
4. Exam (mid-term only)


---
# Assignments

- Homework (x3)

- Mid-term

- Case Study

- Policy discussion


---
# Grading

 Component     | Weight
 --------------| ------------
 Homework (x3) | 45% 
 Mid-term      | 20%
 Case Study    | 30%
 Discussion    | 5%


---
# Some expectations
- This is an <b>economics</b> class first
- Need some calculus to think things through formally
  - Nothing more than derivatives
  - For review, see [practice problems](files/practice_problems.pdf) and [solutions](files/practice_poblems_solutions.pdf)
  - If you can do this review, you're in good shape

