---
title: "Module 2: Physician Agency and Treatment Decisions"
subtitle: "Agency and fee-for-service payments"
author: Ian McCarthy, Emory University
date: Econ 372, Spring 2021
header-includes: 
  - \usepackage{tikz}
  - \usepackage{amsmath}
  - \usepackage{pgf}
  - \usepackage[xcolor=pst]{pstricks}
  - \usepackage{pgfshade}
  - \usepackage{pdftools}
output:
  xaringan::moon_reader:  
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
knit: pagedown::chrome_print      
---

<!-- Adjust some CSS code for font size and maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools)
```

# What are fee-for-service payments?

- Fee-for-service (FFS) means providers are paid a set payment for a well-defined service
- More services $=$ more payments
- Potentially encourages overuse 
- [Supplemental Google Slides from 3/2](https://docs.google.com/presentation/d/1mDrHqX3csv8nBaNSmmq5IHjq75E2k50mshLERnrEsfE/edit?usp=sharing)

---
# How are FFS payments calculated?

- Until 1983, Medicare paid hospitals on a "cost-plus" basis
- Can you think of some problems with this approach?

---
count: false

# How are FFS payments calculated?

- In 1983, Medicare switched to a "Prospective Payment System
- PPS: fixed payment that hospitals know they will receive in advance
- **Fixed** based on the Diagnosis Related Group (DRG) code and other hospital characteristics

---
count: false

# How are FFS payments calculated?

Let's work through a simple example:

1. PPS "standardized" amounts (one for labor and one for capital)
2. Adjust labor amount for wage index and add standardized capital amount
3. Multiply by DRG weight
4. Multiply by disproportionate share and teaching hospital adjustments (if relevant)
5. Account for outliers


---
count: false

# How are FFS payments calculated?

**Step 1**<br>
$\left((\text{Labor} \times \text{Wage Index}) + \text{Capital} \right)*\text{DRG Weight}=\text{Base Payment}$

**Step 2**<br>
$\text{Base Payment}\times (1 + \text{DSH Adj} + \text{Teaching Adj}) = \text{Final Payment}$

--

Let's look at some of these in real life...

---
# In-class Problem: Agency and fixed prices

Assume $B(x)=4x^{1/2}$, $NB^{0}=0$, anc $c=1$. Further assume that prices are fixed administratively at, $\bar{p}=2$. Note that, in this case, we work only off of the patient's net benefit constraint.

1. What is the physician's and patient's optimal amount of care provided?
2. The government is considering increasing the price to $\bar{p}=3$. What are the new optimal levels of care for physicians and patients at this new price?
3. How would the price change affect the difference between the patient and physician's optimal amounts?

---
# Comparative statics
An increase in the administratively set price leads to a <b>decrease</b> in quantity of services provided. And vice versa, a reduction in price leads to an <b>increase</b> in quantity provided. Why?

--
$$\begin{align*}
b(x)\frac{\mathrm{d}x}{\mathrm{d}p} - x - p\frac{\mathrm{d}x}{\mathrm{d}p} &= 0 \\
\frac{\mathrm{d}x}{\mathrm{d}p} = \frac{-x}{p-b(x)} &< 0.
\end{align*}$$

---
# Why does this matter?

Say we want to reduce health care utilization, and we try to do so by cutting payments. Will this work?

---
# Fixed payments in practice

Real life is a little more complicated!

- Often more than one treatment to consider
- Often more than one payer (private and public) to consider
