---
title: "Module 2: Physician Agency and Treatment Decisions"
subtitle: "Current issues in health care payments"
author: Ian McCarthy, Emory University
date: Econ 372, Spring 2021
header-includes: 
  - \usepackage{tikz}
  - \usepackage{amsmath}
  - \usepackage{pgf}
  - \usepackage[xcolor=pst]{pstricks}
  - \usepackage{pgfshade}
  - \usepackage{pdftools}
output:
  xaringan::moon_reader:  
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
---

<!-- Adjust some CSS code for font size and maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools)
```


# Major Public Payors

1. Medicare
2. Medicaid

---
# Background on Medicare
- Created by the Social Security Act in 1965
- Originally health insurance to those 65 years of age and older
- Expanded to include certain disabilities (20% now below age 65)
- Consists of four parts:
  1. Part A: Hospital Insurance
  2. Part B: "Medical" Insurance (physician visits and outpatient care)
  3. Part C: Private supplemental care (Medicare plus Choice, now Medicare Advantage)
  4. Part D: Prescription Drug Coverage

---
# Medicare Part A
- Automatic enrollment for anyone 65 and older who worked over their lifetime
- Financed with combination of payroll tax (current workers) and cost-sharing (deductibles, etc.)
- Funds exist as part of "Federal Hospital Insurance Trust Fund"...can't finance through debt
- Benefit structure:
  - Very good for short inpatient stays
  - Very bad for major problems with long stays
  - Doesn't cover nursing home care beyond 30 days

---
# Medicare Part B
- Voluntary, but almost everyone enrolls
- Requires monthly premium ($144 in 2020)
- Small deductible and 20% co-insurance


---
# Medicare Part C
- Private insurance provision of Medicare benefits
- Formally created under Balanced Budget Act in 1997 (existed informally before)
- Heavily revised in Medicare Modernization Act in 2003
- Medicare pays insurers a risk-adjusted amount to enroll a given beneficiary
- Broader benefits than Part A and B, often with $0 additional premiums, but restrictive networks

---
# Medicare Part D
- Created under the Medicare Modernization Act in 2003
- Private insurance for prescription drugs
- Insurers receive payments from Medicare to enroll a given beneificiary (much like Part C)
- Many insurers offer a combined Part C+D plan

---
# Privatization of Medicare
- Medicare Advantage (both Parts C and D) has been well-received and generally thought to be a success story for Medicare benefits
- Accounts for nearly 40% of total Medicare enrollees
- Some early difficulties with adverse selection and risk-adjustment
- Still slightly sicker people staying in traditional Medicare
- Could be a <b>big</b> part of any future "Medicare-for-all" type program

---
# Medicare payments
- Prospective payment system
- Begin with two "base" rates:
  - Operating base payment rates, <span>&#36;</span>5,797 in 2020
  - Capital base payment rates, <span>&#36;</span>462 in 2020
- Adjustments:
  - Diagnosis Related Group (higher adjustments for more complicated things)
  - Academic Medical Center
  - Disproportionate Share


---
# Background on Medicaid
- Also created by the Social Security Act in 1965
- Originally provided health insurance to people receiving "Aid to Families with Dependent Children", mainly extremely poor families
- Expanded over time with different rules by state
- Huge program: about 40% of births are covered by Medicaid/CHIP and 1 in 3 birhts!

---
# ACA and Medicaid Expansion
- Big part of ACA was Medicaid expansion
- Originally mandatory but made voluntary by Supreme Court
- Expansion covers all adults (with or without children) below age 65 and with incomes below 138% of the federal poverty line ($35,535 for family of 4 in 2020)
  
---
# Medicaid Funding
- Paid for by states and federal funding
- State funding is matched by federal funds, and the match amount depends on the state's per capita income
- Incentivizes services to be provided by Medicaid that historically may not be

---
# Medicaid Benefits
- Pretty generous coverage
- Low to no copayments, deductibles, co-insurance
- Usually covers dental, vision, hospitals, and physician services
- Covers long term care (unlike Medicare). About 40% of all long term care is paid for by Medicaid.
- Growth in Medicaid managed care

---
# Medicaid Payments
- Works similarly to Medicare with a base rate plus adjustments
- Base rates vary by state Medicaid agencies
- Adjustments (or supplemental payments) consist of:
  - Disproportionate share adjustments 
  - Other (non-DSH) adjustments
  - Account for a little less than half of total Medicaid payments on average


---
# Pay for performance
There are three main pay for performance programs employed in Medicare right now:
1. Hospital Readmission Reduction Program
2. [Value-based Purchasing](https://www.cms.gov/Medicare/Quality-Initiatives-Patient-Assessment-Instruments/Value-Based-Programs/HVBP/Hospital-Value-Based-Purchasing)
3. [Quality Payment Program](https://qpp.cms.gov/about/qpp-overview) for physicians: Merit-based Incentive Payment System (MIPS) and Advanced Alternative Payment Models (APMs)

---
# Capitated Payments
There are two forms of capitated payments in Medicare now:
1. [Bundled Payments](https://innovation.cms.gov/initiatives/bundled-payments/)
2. [Accountable Care Organizations](https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/ACO/)

---
# Other payment issues

Information and Consumer Choice: 
1. [Hospital Compare](https://www.medicare.gov/hospitalcompare/search.html?)
2. [Penalty Information](https://khn.org/news/hospital-penalties/)
