---
title: "Module 1: Health Insurance"
subtitle: "Health insurance policies in the U.S."
author: Ian McCarthy | Emory University
date: Econ 372 #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{tikz}
  - \usepackage{amsmath}
  - \usepackage{pgf}
  - \usepackage[xcolor=pst]{pstricks}
  - \usepackage{pgfshade}
  - \usepackage{pdftools}
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
knit: pagedown::chrome_print
---

<!-- Adjust some CSS code for font size and maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes,
               scales, gganimate, gapminder, gifski, png, tufte, plotly, OECD,
               ggrepel, survey, foreign, devtools, pdftools)
```

# History of health insurance in the U.S.
Only developed country to rely on employer provided insurance market - why?<br>

--

1. Stabalization act of 1942 (wages frozen but not benefits)

2. Tax exemption for insurance expenditures (1954)

---
# Current policy
1. Increasingly reliant on private market, even for public insurance programs, where adverse selection is most salient
2. [Health insurance exchanges](https://www.cms.gov/CCIIO/Programs-and-Initiatives/Health-Insurance-Marketplaces/index.html)
3. [Individual mandate](https://www.healthcare.gov/fees/fee-for-not-being-covered/)
4. [Premium and cost-sharing subsidies](http://www.kff.org/health-reform/issue-brief/explaining-health-care-reform-questions-about-health/)
5. [Insurer subsidies](http://www.kff.org/health-reform/issue-brief/explaining-health-care-reform-risk-adjustment-reinsurance-and-risk-corridors/)
6. Medicaid expansion
7. [Risk adjustment](https://www.cms.gov/Medicare/Health-Plans/MedicareAdvtgSpecRateStats/Downloads/RTC-Dec2018.pdf)


---
# Current debate

1. Individual mandate went to the supreme court, as did the (originally) mandatory Medicaid expansion

2. Penalty for individual mandate has since been reduced to $0 (so really no mandate anymore). 

3. Trump administration refused to pay cost-sharing subsidies

---
# Common questions
1. Why so much opposition to the ACA?
2. Why repeal the existing provisions in the ACA that cover pre-existing conditions?
3. What are the differences between employer-provided health care and health care provided by the ACA?
4. Other than insurance, in what ways does the ACA affect health care?
5. How does the government support the ACA?
6. What are the problems with the ACA and what are the replacement options? [fun "medicare for all" dashboard](http://shift.cidma.us/)


---
# In context
We motivated this entire section of the class with the example of Humana withdrawing from the ACA exchanges. This example and our policy discussion highlight at least four things:

1. Patient health has a major effect on insurer costs (we showed this with some basic problems).
2. There is theoretically less available profit with a really sick patient pool (we showed this too). Budget constraints compound this problem.
3. With community ratings, standard insurance market will leave some people uninsured who are willing and able to purchase.
4. Lots of policy levers to address these issues, but the magnitude of each lever is an empirical question.